services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzWebPushBundle\Controller\WebPushSWController: ~

    Edgar\EzWebPushBundle\Controller\WebPushController:
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]
