edgar.ezwebpush.profile:
    path: /webpush
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:profile'

edgar.ezwebpush.register:
    path: /webpush/register
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:register'

edgar.ezwebpush.unregister:
    path: /webpush/unregister
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:unregister'

edgar.ezwebpush.message:
    path: /bookmark/message
    methods: [ "POST" ]
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:message'
