edgar.ezwebpush.profile:
    path: /
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:profile'

edgar.ezwebpush.register:
    path: /register
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:register'

edgar.ezwebpush.unregister:
    path: /unregister
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:unregister'

edgar.ezwebpush.message:
    path: /message
    methods: [ "POST" ]
    defaults:
        _controller: 'EdgarEzWebPushBundle:WebPush:message'
