imports:
    - { resource: controllers.yml }
    - { resource: components.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzWebPushBundle\EventListener\ProfileConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: edgar_ezuiprofile.menu_configure.profile_account_sidebar_right, method: onMenuConfigure }

    Edgar\EzWebPushBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.content_sidebar_right, method: onMenuConfigure }

    Edgar\EzWebPushBundle\EventListener\SWListener:
        public: true
        arguments:
            $fragmentPath: "%fragment.path%"
        tags:
            - { name: kernel.event_subscriber }

    Edgar\EzWebPush\Notification\WebPushNotificationHandler: ~

    Edgar\EzWebPushBundle\Service\WebPushService:
        public: true
        arguments:
            $subject: '%edgar_ez_web_push.subject%'
            $privateKey: '%edgar_ez_web_push.vapid_private_key%'
            $publicKey: '%edgar_ez_web_push.vapid_public_key%'
            $imageVariationService: '@ezpublish.image_alias.imagine.variation.imagine_alias_generator'
